[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_NETLIFY_FUNCTION_URL"

[dev]
  command = "npm run dev"
  port = 8888
  framework = "next"
  functions = "netlify/functions"
